# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(671, 407)
        Form.setStyleSheet("/* 전체 배경, 기본 폰트 */\n"
"QWidget {\n"
"    background-color: #ffffff;\n"
"    font-family: \'Malgun Gothic\';\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"/* 버튼 */\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #005A9E;\n"
"}\n"
"\n"
"/* QLineEdit만 폰트 더 작게 */\n"
"QLineEdit {\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 14px;  /* 줄인 부분 */\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"/* QTextEdit (메뉴 설명칸 등) */\n"
"QTextEdit {\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 16px;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"/* QComboBox */\n"
"QComboBox {\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    background-color: #ffffff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"/* 레이블 */\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    color: #333333;\n"
"}")
        self.menu_img = QtWidgets.QGraphicsView(Form)
        self.menu_img.setGeometry(QtCore.QRect(30, 60, 241, 151))
        self.menu_img.setObjectName("menu_img")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(90, 240, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(340, 70, 230, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(340, 120, 230, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 170, 230, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(340, 230, 230, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 290, 141, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 290, 141, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 350, 101, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 350, 101, 41))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "사진 선택"))
        self.comboBox.setItemText(0, _translate("Form", "카테고리 지정"))
        self.lineEdit.setText(_translate("Form", "메뉴명"))
        self.lineEdit_2.setText(_translate("Form", "가격"))
        self.lineEdit_3.setText(_translate("Form", "메뉴 설명"))
        self.pushButton_2.setText(_translate("Form", "필수옵션 설정"))
        self.pushButton_3.setText(_translate("Form", "추가옵션 설정"))
        self.pushButton_4.setText(_translate("Form", "취소"))
        self.pushButton_5.setText(_translate("Form", "등록"))
